### ISSUE TITLE
What is the correct syntax to specify multiple channels to exclude from deletion?

### ISSUE THREAD

**Issue by larryqiann** [c-edw/discord-delete#47]
I have tried to use the syntax ./discord-delete-darwin-arm64 partial -v -o 60 --skip 8xxxxxxx 6xxxxxxx 6xxxxxxxxx, but the application appears to have deleted some threads with those channel IDs.

Is there any way to have the application show what it believes the excluded channels are?

Thanks!

**Comment by larryqiann** [comment]
After looking at the code for "pflag" which is where the flag parsing function is from, it seems that the values have to be comma-separated.

As such, I'm guessing it's more like --skip="8xxxxx,6xxxxx,6xxxxxxx" instead

[https://github.com/spf13/pflag/blob/master/string_slice.go](url)
```
// StringSliceVar defines a string flag with specified name, default value, and usage string.
// The argument p points to a []string variable in which to store the value of the flag.
// Compared to StringArray flags, StringSlice flags take comma-separated value as arguments and split them accordingly.
// For example:
//   --ss="v1,v2" --ss="v3"
// will result in
//   []string{"v1", "v2", "v3"}
func StringSliceVar(p *[]string, name string, value []string, usage string) {
	CommandLine.VarP(newStringSliceValue(value, p), name, "", usage)
}

// StringSliceVarP is like StringSliceVar, but accepts a shorthand letter that can be used after a single dash.
func StringSliceVarP(p *[]string, name, shorthand string, value []string, usage string) {
	CommandLine.VarP(newStringSliceValue(value, p), name, shorthand, usage)
}
```

**Comment by lillelilje** [comment]
This is well documented in the https://github.com/cedws/discord-delete/wiki/Skipping-specific-channels page. This is also linked directly from the main readme.

Basically: `./discord-delete partial -s 777813370090815590 -s 796286628817272843 -s 805364751726280745`

Hopefully that's helpful :)

**Comment by cedws** [comment]
Hope the above answers your question.

**Comment by larryqiann** [comment]
Thank you for the update. I am sorry I missed this, I do remember being on that documentation page but must have missed the example with multiple. (might have also clicked on the wrong version)
